# Generated by Django 3.1 on 2020-08-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_messanger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('age', models.CharField(blank=True, max_length=400, null=True)),
                ('mobile', models.CharField(blank=True, max_length=400, null=True)),
                ('place', models.CharField(blank=True, max_length=400, null=True)),
                ('booking_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='messanger',
            name='MessangerMessage',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
